steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cat-food-finder/rasa-bot', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cat-food-finder/rasa-bot']
  # Deploy container image to Cloud Run -https://cloud.google.com/sdk/gcloud/reference/run/services/update
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'rasa-bot-api',
        '--image',
        'gcr.io/chatala/rasa-bot',
        '--region',
        'us-east1',
        '--platform',
        'managed',
        '--memory',
        '2Gi',
        '--allow-unauthenticated',
      ]
images:
  - gcr.io/chatala/rasa-bot
